# This is a basic workflow to help you get started with Actions

name: VVS - Projeto Final

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      
      - name: Stop MySQL
        run: sudo killall mysqld mysqld_safe
      
      
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          mysql root password: '123581321'
          mysql database: 'vvs_test'
          mysql user: 'pradota'
          mysql password: '123581321'
          
      - name: Configure Yii project
        run: |
          composer update
          php ./init --env=Development --overwrite=All --delete=All
          cp ./common/config/git-local.php ./common/config/main-local.php
          cp ./common/config/git-local.php ./common/config/test-local.php
          cd ./common/config          
      
          
      - name: Yii database migrate
        run: |
          sudo service mysql status
          php ./yii migrate --interactive=0
          php ./yii_test migrate --interactive=0

      - name: Run Unit and Functional Tests
        run: vendor/bin/codecept run
      
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: --browsers 'firefox' last-versions 1
      
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@v0.0.0
        with: 
          geckodriver-version: latest
          
#      - name: Run Acceptance Tests
#        run: |
#          composer require codeception/module-webdriver --dev
#          mv ./frontend/tests/acceptance.suite.yml.example ./frontend/tests/acceptance.suite.yml
#          php -S 127.0.0.1:8080 -t frontend/web
#          vendor/bin/codecept build -- -c frontend          
#          vendor/bin/codecept run acceptance -- -c frontend
        
          
    
          
