# This is a basic workflow to help you get started with Actions

name: VVS - Projeto Final

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: ${{ secrets.DB_ROOT_PASS }}
          mysql database: 'vvs_test'
          mysql user: 'pradota'
          mysql password: ${{ secrets.DB_ROOT_PASS }}
          
      - name: Configure Yii project
        run: |
          composer update
          php ./init --env=Development --overwrite=All --delete=All
          cp ./common/config/git-local.php ./common/config/main-local.php
          cp ./common/config/git-local.php ./common/config/test-local.php
          cd ./common/config          
              
      - name: Yii database migrate
        run: |
          php ./yii migrate --interactive=0
          php ./yii_test migrate --interactive=0

      - name: Run Unit and Functional Tests
        run: | 
          vendor/bin/codecept run          
      
      - name: Setup Geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
          tar -xvzf geckodriver*
          chmod +x geckodriver
          export PATH=$PATH:/var/www/html/advanced/geckodriver.
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: '15'
          distribution: 'adopt'
      
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
        with:
          chromedriver-version: '92.0.4515.107'
                       
      - name: Prepare Aceptance Environment
        run: |
          google-chrome --version
          ls -l /usr/bin/ | grep chrome
          mv ./frontend/tests/acceptance.suite.yml.example ./frontend/tests/acceptance.suite.yml
          composer require codeception/module-webdriver --dev
          vendor/bin/codecept build -- -c frontend  
          
          wget https://selenium-release.storage.googleapis.com/3.10/selenium-server-standalone-3.10.0.jar
          java -jar selenium-server-standalone-3.10.0.jar -enablePassThrough false &
          php -S 127.0.0.1:8080 -t frontend/web &  
          
      - name: Run Acceptance Tests
        run: |                                                
          vendor/bin/codecept run acceptance -- -c frontend
        
          
    
          
